"""add_kapak_resmi_column

Revision ID: 16089448691a
Revises: 21f7d1e02a5c
Create Date: 2025-05-04 19:17:51.618967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16089448691a'
down_revision = '21f7d1e02a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Kitaplar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('KapakResmi', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Kitaplar', schema=None) as batch_op:
        batch_op.drop_column('KapakResmi')

    # ### end Alembic commands ###
