"""initial migration

Revision ID: 853bef6b5bb5
Revises: 
Create Date: 2025-05-12 15:03:56.668016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853bef6b5bb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Kategoriler',
    sa.Column('KategoriID', sa.Integer(), nullable=False),
    sa.Column('Ad', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('KategoriID'),
    sa.UniqueConstraint('Ad')
    )
    op.create_table('Musteriler',
    sa.Column('MusteriID', sa.Integer(), nullable=False),
    sa.Column('Ad', sa.String(length=100), nullable=False),
    sa.Column('Soyad', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('Telefon', sa.String(length=20), nullable=True),
    sa.Column('KayitTarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('MusteriID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Personeller',
    sa.Column('PersonelID', sa.Integer(), nullable=False),
    sa.Column('KullaniciAdi', sa.String(length=50), nullable=False),
    sa.Column('SifreHash', sa.String(length=255), nullable=False),
    sa.Column('Ad', sa.String(length=100), nullable=False),
    sa.Column('Soyad', sa.String(length=100), nullable=False),
    sa.Column('Rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('PersonelID'),
    sa.UniqueConstraint('KullaniciAdi')
    )
    op.create_table('Yayinevleri',
    sa.Column('YayineviID', sa.Integer(), nullable=False),
    sa.Column('Ad', sa.String(length=255), nullable=False),
    sa.Column('Adres', sa.Text(), nullable=True),
    sa.Column('Telefon', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('YayineviID'),
    sa.UniqueConstraint('Ad')
    )
    op.create_table('Yazarlar',
    sa.Column('YazarID', sa.Integer(), nullable=False),
    sa.Column('Ad', sa.String(length=100), nullable=False),
    sa.Column('Soyad', sa.String(length=100), nullable=False),
    sa.Column('Biyografi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('YazarID')
    )
    op.create_table('Kitaplar',
    sa.Column('KitapID', sa.Integer(), nullable=False),
    sa.Column('ISBN', sa.String(length=13), nullable=False),
    sa.Column('Ad', sa.String(length=255), nullable=False),
    sa.Column('YayinYili', sa.Integer(), nullable=True),
    sa.Column('SayfaSayisi', sa.Integer(), nullable=True),
    sa.Column('Fiyat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('StokAdedi', sa.Integer(), nullable=False),
    sa.Column('YayineviID', sa.Integer(), nullable=False),
    sa.Column('KategoriID', sa.Integer(), nullable=False),
    sa.Column('KapakResmi', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['KategoriID'], ['Kategoriler.KategoriID'], ),
    sa.ForeignKeyConstraint(['YayineviID'], ['Yayinevleri.YayineviID'], ),
    sa.PrimaryKeyConstraint('KitapID'),
    sa.UniqueConstraint('ISBN')
    )
    op.create_table('Satislar',
    sa.Column('SatisID', sa.Integer(), nullable=False),
    sa.Column('MusteriID', sa.Integer(), nullable=True),
    sa.Column('SatisTarihi', sa.DateTime(), nullable=False),
    sa.Column('ToplamTutar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('PersonelID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MusteriID'], ['Musteriler.MusteriID'], ),
    sa.ForeignKeyConstraint(['PersonelID'], ['Personeller.PersonelID'], ),
    sa.PrimaryKeyConstraint('SatisID')
    )
    op.create_table('KitapYazarlari',
    sa.Column('KitapID', sa.Integer(), nullable=False),
    sa.Column('YazarID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['KitapID'], ['Kitaplar.KitapID'], ),
    sa.ForeignKeyConstraint(['YazarID'], ['Yazarlar.YazarID'], ),
    sa.PrimaryKeyConstraint('KitapID', 'YazarID')
    )
    op.create_table('SatisDetaylari',
    sa.Column('SatisDetayID', sa.Integer(), nullable=False),
    sa.Column('SatisID', sa.Integer(), nullable=False),
    sa.Column('KitapID', sa.Integer(), nullable=False),
    sa.Column('Adet', sa.Integer(), nullable=False),
    sa.Column('BirimFiyat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['KitapID'], ['Kitaplar.KitapID'], ),
    sa.ForeignKeyConstraint(['SatisID'], ['Satislar.SatisID'], ),
    sa.PrimaryKeyConstraint('SatisDetayID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SatisDetaylari')
    op.drop_table('KitapYazarlari')
    op.drop_table('Satislar')
    op.drop_table('Kitaplar')
    op.drop_table('Yazarlar')
    op.drop_table('Yayinevleri')
    op.drop_table('Personeller')
    op.drop_table('Musteriler')
    op.drop_table('Kategoriler')
    # ### end Alembic commands ###
